# Generated by Django 5.1.1 on 2024-09-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_localauthority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalAuthority',
        ),
    ]
