# Generated by Django 5.1.1 on 2024-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_localauthority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthority',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
