# Generated by Django 5.1.1 on 2024-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_localauthority_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthority',
            name='description',
            field=models.TextField(),
        ),
    ]
