# Generated by Django 5.1.1 on 2024-09-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_image'),
        ('trail', '0005_remove_trail_coordinates_coordinate_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.coordinate'),
        ),
    ]
