# Generated by Django 5.1.1 on 2024-09-07 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='mode',
        ),
        migrations.AlterField(
            model_name='review',
            name='travel_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.travelmode'),
        ),
        migrations.AlterField(
            model_name='travelmode',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.travelmode'),
        ),
    ]
