# Generated by Django 5.1.1 on 2024-09-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0004_alter_coordinate_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.trail'),
        ),
    ]
