# Generated by Django 5.1.1 on 2024-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0005_remove_trail_coordinates_coordinate_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lon',
            field=models.CharField(max_length=255),
        ),
    ]
