# Generated by Django 5.1.1 on 2024-09-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0006_alter_coordinate_lat_alter_coordinate_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landmark/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark_coordinate', to='trail.coordinate')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.trail')),
            ],
        ),
    ]
