# Generated by Django 5.1.1 on 2024-09-07 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trail', '0006_alter_coordinate_lat_alter_coordinate_lon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_checkpoints', models.JSONField(blank=True, default=list)),
                ('current_coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_navigation_set', to='trail.coordinate')),
                ('last_checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_navigation_set', to='trail.coordinate')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
